{
 "title": "Postgresql Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Postgres Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select version from db_info ;" }
   ]
  },
  {
   "title": "Tables",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select name, schema, oid from tables ;"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select \n i.name as \"Index Name\",\n t.name as \"Table Name\",\n i.schema as \"Schema\" \nFROM indexes i JOIN tables t on t.oid = i.table_oid"
    }
   ]
  }
 ]
}