{
 "title": "PG Stat Activity History",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "As Of",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "    SELECT sample_time\n    FROM psa\n    WHERE $__timeFilter(sample_time)\n    ORDER BY sample_time LIMIT 1;"
    }
   ]
  },
  {
   "title": "Available Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "  SELECT DISTINCT(sample_time), 1 as Available\n    FROM psa\n    WHERE $__timeFilter(sample_time)\n    ORDER by sample_time;"
    }
   ]
  },
  {
   "title": "PG Stat Activity",
   "type": "table",
   "gridPos": { "h": 20, "w": 21, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "WITH latest AS (\n    SELECT sample_time as sample_time\n    FROM psa\n    WHERE $__timeFilter(sample_time)\n    ORDER by sample_time desc LIMIT 1\n)\nselect \npsa.*,\nGREATEST(0, EXTRACT(EPOCH FROM (psa.sample_time - psa.query_start)))  as query_runtime,\nGREATEST(0, EXTRACT(EPOCH FROM (psa.sample_time - psa.xact_start))) as time_in_transaction\nfrom psa, latest\nwhere psa.sample_time = latest.sample_time;"
    }
   ]
  }
 ]
}